apiVersion: v1
kind: Service
metadata:
  name: langchain-free
  namespace: langchain-free
spec:
  selector:
    app: langchain-free
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
