apiVersion: apps/v1
kind: Deployment
metadata:
  name: free-agent-lab-4-1
  namespace: ai-ml-lab-4-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: free-agent-lab-4-1
  template:
    metadata:
      labels:
        app: free-agent-lab-4-1
    spec:
      containers:
        - name: free-agent-lab-4-1
          image: free-agent-lab-4-1:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
