apiVersion: v1
kind: Service
metadata:
  name: free-agent-lab-4-1
  namespace: ai-ml-lab-4-1
spec:
  type: ClusterIP
  selector:
    app: free-agent-lab-4-1
  ports:
    - port: 8000
      targetPort: 8000
