apiVersion: v1
kind: Service
metadata:
  name: ai-lab-2-1-free
  labels:
    app: ai-lab-2-1-free
spec:
  type: ClusterIP
  selector:
    app: ai-lab-2-1-free
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
